name: build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install GnuPG2
      run: |
        sudo apt-get update && sudo apt-get -y install gnupg2
        mkdir ~/.gnupg && chmod 700 ~/.gnupg
        echo use-agent >> ~/.gnupg/gpg.conf
        echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
        echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
        echo allow-preset-passphrase >> ~/.gnupg/gpg-agent.conf
        chmod 600 ~/.gnupg/*
        echo RELOADAGENT | gpg-connect-agent
        echo $PGP_SECRET | base64 --decode --ignore-garbage | gpg --import --no-tty --batch --yes
        /usr/lib/gnupg2/gpg-preset-passphrase --passphrase $PGP_PASSPHRASE
      env:
        PGP_SECRET: ${{secrets.PGP_SECRET}}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew uploadArchives -Psigning.gnupg.keyName=0D7CEE98
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
